---
name: eliud_pkg_membership_model
description: eliud_pkg_membership_model is the model package for the package eliud_pkg_membership.
  More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_membership_model
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core_main: ^1.0.2
  eliud_pkg_etc_model: ^1.0.0
  eliud_core_helpers: ^1.0.0
  bloc: ^8.1.2
  cloud_firestore: ^4.13.5
  collection: ^ 1.18.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator: ^1.1.7
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
